# -*- coding: utf-8 -*-
"""Generate landing/ assets from Particle Source extract. Run from repo root."""
from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PARTICLE = ROOT / "Particle"
if not (PARTICLE / "experiments" / "cymatics" / "index.html").is_file():
    PARTICLE = ROOT / "_extract_particle" / "Particle"
SRC_CSS = PARTICLE / "css" / "particle-love.com" / "css" / "index.css"
SRC_JS = PARTICLE / "js" / "particle-love.com" / "js" / "index.js"
SRC_THREE = PARTICLE / "js" / "particle-love.com" / "js" / "three.r76.min.js"
SRC_TW = PARTICLE / "js" / "particle-love.com" / "js" / "TweenMax.min.js"
LANDING = ROOT / "landing"
OUT_CSS = LANDING / "css" / "landing.css"
OUT_JS = LANDING / "js" / "particle-landing.js"

ROOT_HEADER = """/* Scoped for Cymatics Portal landing overlay — generated by _landing_assets.py */
#landing-root {
    position: fixed;
    inset: 0;
    z-index: 9000;
    font-family: 'Courier New', Courier, monospace;
    font-style: normal;
    background-color: #060a11;
    overflow: hidden;
    -webkit-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
}

"""


def _prefix_selector_line(sel: str) -> str:
    sel = sel.strip()
    if not sel or sel.startswith("#landing-root"):
        return sel
    parts = [p.strip() for p in sel.split(",")]
    out = []
    for p in parts:
        if p.startswith("#landing-root"):
            out.append(p)
        elif p.startswith("::") or p.startswith(":"):
            out.append(f"#landing-root {p}")
        else:
            out.append(f"#landing-root {p}")
    return ", ".join(out)


def scope_landing_css(css: str) -> str:
    css = re.sub(r"html\s*\{[^}]*\}", "", css, count=1)
    css = re.sub(r"body\s*\{[^}]*\}", "", css, count=1)
    lines = css.split("\n")
    out_lines: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if not stripped:
            out_lines.append(line)
            continue
        if stripped.startswith("/*"):
            out_lines.append(line)
            continue
        if stripped.startswith("@media"):
            out_lines.append(line)
            continue
        if stripped.startswith("@"):
            out_lines.append(line)
            continue

        if "{" in line:
            idx = line.index("{")
            before = line[:idx]
            after = line[idx:]
            indent = before[: len(before) - len(before.lstrip())]
            sel = before.strip()
            if sel:
                new_sel = _prefix_selector_line(sel)
                out_lines.append(f"{indent}{new_sel} {after}")
            else:
                out_lines.append(line)
        else:
            out_lines.append(line)
    return ROOT_HEADER + "\n".join(out_lines).strip() + "\n"


def patch_particle_js(js: str) -> str:
    """Point texture loads to ./landing/images/ (config.assetPath + images/motion_blur.png)."""
    repl_obj = (
        '(typeof window!=="undefined"&&window.__pmAssetPath)?'
        'window.__pmAssetPath:"./landing/"'
    )
    repl_assign = (
        '((typeof window!=="undefined"&&window.__pmAssetPath)?'
        'window.__pmAssetPath:"./landing/")'
    )
    js2 = js.replace('assetPath:"./"', f"assetPath:{repl_obj}")
    js2 = js2.replace('assetPath="./"', f"assetPath={repl_assign}")
    # Four u_color lerps: Julia backdrop technicolor (same cosine mix as engine
    # `juliaFractalBackdropPaletteRgb` / backdrop defaults pal=0, colorIntensity≈0.55).
    _l_old = "function l(e){n.needsResetWorldMatrix"
    _l_new = (
        "function l(e){this._pmJT=((this._pmJT||0)+e*1.2)%1;var u=this._pmJT,Q=6.28318,O=0,"
        "_pmsat=0.5+0.55*0.5,j=function(t){t=t-Math.floor(t);var h=t*3+O,"
        "x=0.5+0.5*Math.cos(Q*h),y=0.5+0.5*Math.cos(Q*(h+0.33)),"
        "z=0.5+0.5*Math.cos(Q*(h+0.67));"
        "return{x:0.5*(1-_pmsat)+x*_pmsat,y:0.5*(1-_pmsat)+y*_pmsat,z:0.5*(1-_pmsat)+z*_pmsat}};"
        "var J0=j(u),J1=j(u+0.25),J2=j(u+0.5),J3=j(u+0.75);"
        "this.color1.setRGB(J0.x,J0.y,J0.z);this.color2.setRGB(J1.x,J1.y,J1.z);"
        "this.color3.setRGB(J2.x,J2.y,J2.z);this.color4.setRGB(J3.x,J3.y,J3.z);"
        "n.needsResetWorldMatrix"
    )
    if _l_old not in js2:
        raise SystemExit("patch_particle_js: particle motion l(e) hook not found (source changed?)")
    js2 = js2.replace(_l_old, _l_new, 1)

    # Low-tier bootstrap at WebGL init: bridge Low click fires later; avoids 512²+MB hitch until handlers run.
    # Stock c()/mouse smoothing unchanged.
    _ptex_old = "particlesMotionTextureWidth=512,n.particlesMotionTextureHeight=512"
    _ptex_new = "particlesMotionTextureWidth=256,n.particlesMotionTextureHeight=256"
    if _ptex_old not in js2:
        raise SystemExit("patch_particle_js: particlesMotionTexture defaults not found (source changed?)")
    js2 = js2.replace(_ptex_old, _ptex_new, 1)
    _mb_old = 'n.motionBlur=!0;var o=n.motionBlurQualityMap'
    _mb_new = 'n.motionBlur=!1;var o=n.motionBlurQualityMap'
    if _mb_old not in js2:
        raise SystemExit("patch_particle_js: motionBlur default not found (source changed?)")
    js2 = js2.replace(_mb_old, _mb_new, 1)
    _mbq_old = 'n.motionBlurQualityList=r(o),n.motionBlurQuality="high"'
    _mbq_new = 'n.motionBlurQualityList=r(o),n.motionBlurQuality="low"'
    if _mbq_old not in js2:
        raise SystemExit("patch_particle_js: motionBlurQuality default not found (source changed?)")
    js2 = js2.replace(_mbq_old, _mbq_new, 1)
    _dpr_hook_old = "h=b.renderer,f=b.scene"
    _dpr_hook_new = (
        "h=b.renderer,h.setPixelRatio(Math.min(1.25,"
        '(typeof window!="undefined"?window.devicePixelRatio:1)||1)),f=b.scene'
    )
    if _dpr_hook_old not in js2:
        raise SystemExit("patch_particle_js: renderer assign (h=b.renderer) hook not found (source changed?)")
    js2 = js2.replace(_dpr_hook_old, _dpr_hook_new, 1)

    return js2


def main() -> None:
    if not SRC_CSS.is_file():
        raise SystemExit(f"Missing {SRC_CSS}")
    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    (LANDING / "js").mkdir(parents=True, exist_ok=True)
    (LANDING / "images").mkdir(parents=True, exist_ok=True)

    scoped = scope_landing_css(SRC_CSS.read_text(encoding="utf-8"))
    # Hero is title-only (overlay has no .logo-byline); keep block compact vs two-line layout.
    scoped = scoped.replace("min-height: 77px;", "min-height: 56px;", 1)
    scoped2, n_iframe = re.subn(
        r"(#landing-root \.iframe-container \{\n    )width:",
        r"\1position: relative;\n    width:",
        scoped,
        count=1,
    )
    if n_iframe != 1:
        raise SystemExit("_landing_assets: iframe-container position patch not applied")
    scoped = scoped2
    OUT_CSS.write_text(scoped, encoding="utf-8")

    shutil.copyfile(SRC_THREE, LANDING / "js" / "three.r76.min.js")
    shutil.copyfile(SRC_TW, LANDING / "js" / "TweenMax.min.js")
    # landing/js/particle-landing.js — hand-maintained (neon yin-yang iframe + overlay shell).
    # Do not overwrite from Particle index.js; regenerate only if migrating back to Particle Source bundle.
    if not OUT_JS.is_file():
        raise SystemExit(
            "Missing landing/js/particle-landing.js (yin-yang bundle). "
            "Restore from git before running _landing_assets.py."
        )

    print("Wrote", OUT_CSS, "(particle-landing.js unchanged, hand-maintained)")


if __name__ == "__main__":
    main()
