# -*- coding: utf-8 -*-
"""Generate landing/ assets from Particle Source extract. Run from repo root."""
from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PARTICLE = ROOT / "Particle"
if not (PARTICLE / "experiments" / "cymatics" / "index.html").is_file():
    PARTICLE = ROOT / "_extract_particle" / "Particle"
SRC_CSS = PARTICLE / "css" / "particle-love.com" / "css" / "index.css"
SRC_JS = PARTICLE / "js" / "particle-love.com" / "js" / "index.js"
SRC_THREE = PARTICLE / "js" / "particle-love.com" / "js" / "three.r76.min.js"
SRC_TW = PARTICLE / "js" / "particle-love.com" / "js" / "TweenMax.min.js"
LANDING = ROOT / "landing"
OUT_CSS = LANDING / "css" / "landing.css"
OUT_JS = LANDING / "js" / "particle-landing.js"

ROOT_HEADER = """/* Scoped for Cymatics Portal landing overlay — generated by _landing_assets.py */
#landing-root {
    position: fixed;
    inset: 0;
    z-index: 9000;
    font-family: 'Courier New', Courier, monospace;
    font-style: normal;
    background-color: #060a11;
    overflow: hidden;
    -webkit-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
}

"""


def _prefix_selector_line(sel: str) -> str:
    sel = sel.strip()
    if not sel or sel.startswith("#landing-root"):
        return sel
    parts = [p.strip() for p in sel.split(",")]
    out = []
    for p in parts:
        if p.startswith("#landing-root"):
            out.append(p)
        elif p.startswith("::") or p.startswith(":"):
            out.append(f"#landing-root {p}")
        else:
            out.append(f"#landing-root {p}")
    return ", ".join(out)


def scope_landing_css(css: str) -> str:
    css = re.sub(r"html\s*\{[^}]*\}", "", css, count=1)
    css = re.sub(r"body\s*\{[^}]*\}", "", css, count=1)
    lines = css.split("\n")
    out_lines: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if not stripped:
            out_lines.append(line)
            continue
        if stripped.startswith("/*"):
            out_lines.append(line)
            continue
        if stripped.startswith("@media"):
            out_lines.append(line)
            continue
        if stripped.startswith("@"):
            out_lines.append(line)
            continue

        if "{" in line:
            idx = line.index("{")
            before = line[:idx]
            after = line[idx:]
            indent = before[: len(before) - len(before.lstrip())]
            sel = before.strip()
            if sel:
                new_sel = _prefix_selector_line(sel)
                out_lines.append(f"{indent}{new_sel} {after}")
            else:
                out_lines.append(line)
        else:
            out_lines.append(line)
    return ROOT_HEADER + "\n".join(out_lines).strip() + "\n"


def patch_particle_js(js: str) -> str:
    """Point texture loads to ./landing/images/ (config.assetPath + images/motion_blur.png)."""
    repl_obj = (
        '(typeof window!=="undefined"&&window.__pmAssetPath)?'
        'window.__pmAssetPath:"./landing/"'
    )
    repl_assign = (
        '((typeof window!=="undefined"&&window.__pmAssetPath)?'
        'window.__pmAssetPath:"./landing/")'
    )
    js2 = js.replace('assetPath:"./"', f"assetPath:{repl_obj}")
    js2 = js2.replace('assetPath="./"', f"assetPath={repl_assign}")
    # Smoother phased entrance for .menu + Enter Portal (.go-btn): avoid scale-from-near-zero + easeOutBack pop.
    _v_old = (
        'function v(){F.style.display="block",M.set(k[0],{x:136,force3D:!0,opacity:0}),'
        'M.to(k[0],.8,{x:0,force3D:!0,opacity:1,ease:"easeInOutQuint"}),'
        'M.set(k[1],{x:-136,force3D:!0,opacity:0}),'
        'M.to(k[1],.8,{x:0,force3D:!0,opacity:1,ease:"easeInOutQuint"}),'
        'M.to(k[1],.8,{x:0,force3D:!0,opacity:1,ease:"easeInOutQuint"}),'
        'M.set(Y,{scale:.001,force3D:!0,opacity:0}),M.to(Y,.5,{opacity:1}),'
        'M.to(Y,.8,{scale:1,force3D:!0,ease:"easeOutBack"})}'
    )
    # Enter Portal: start sooner (delay 0 on button), ease title/dropdown rows slightly; gentler from-y.
    _v_new = (
        'function v(){F.style.display="block",M.set(F,{opacity:0}),'
        'M.to(F,1.1,{opacity:1,ease:"easeOutSine"}),'
        'M.set(k[0],{x:56,force3D:!0,opacity:0}),'
        'M.to(k[0],1.2,{delay:.04,x:0,force3D:!0,opacity:1,ease:"easeOutCubic"}),'
        'M.set(k[1],{x:-56,force3D:!0,opacity:0}),'
        'M.to(k[1],1.2,{delay:.04,x:0,force3D:!0,opacity:1,ease:"easeOutCubic"}),'
        'M.fromTo(Y,1.05,{opacity:0,scale:.9,y:14,force3D:!0},'
        '{delay:0,opacity:1,scale:1,y:0,force3D:!0,ease:"easeOutCubic"})}'
    )
    if _v_old not in js2:
        raise SystemExit("patch_particle_js: expected landing v() body not found (source changed?)")
    js2 = js2.replace(_v_old, _v_new, 1)
    # Logo (W) + camera: longer, gentler eases so "Cymatics Portal" / scene settle feels less snappy.
    _y_tween_old = (
        "M.to(W,.5,{opacity:1}),M.to(T.camera.position,1,{x:Q.x,y:Q.y,z:Q.z,ease:"
        '"easeOutBack"})'
    )
    _y_tween_new = (
        "M.to(W,.95,{opacity:1,ease:"
        '"easeOutSine"}),M.to(T.camera.position,1.5,{x:Q.x,y:Q.y,z:Q.z,ease:"easeInOutCubic"})'
    )
    if _y_tween_old not in js2:
        raise SystemExit("patch_particle_js: y() logo/camera tweens not found (source changed?)")
    js2 = js2.replace(_y_tween_old, _y_tween_new, 1)
    _y_blur_old = (
        "M.to(I,1,{ratio:0,blurRadius:2.5,amount:1,ease:"
        '"easeOutQuint",onComplete:function(){C.style.pointerEvents="auto",F.style.pointerEvents="auto"}})}'
    )
    _y_blur_new = (
        "M.to(I,1.45,{ratio:0,blurRadius:2.5,amount:1,ease:"
        '"easeOutQuint",onComplete:function(){C.style.pointerEvents="auto",F.style.pointerEvents="auto"}})}'
    )
    if _y_blur_old not in js2:
        raise SystemExit("patch_particle_js: y() motion-blur onComplete not found (source changed?)")
    js2 = js2.replace(_y_blur_old, _y_blur_new, 1)
    # Landing particle field: stabilize timestep (raw delta made speed nonlinear and spiked on hitches).
    _c_old = (
        "function c(e,t){if(!T.skipRendering){e=e||0,T.deltaRatio=e/.016,t=t||Date.now();"
        "var n=T.speed+(1-T.initialAmimation)*e*100;e*=n,"
    )
    _c_new = (
        "function c(e,t){if(!T.skipRendering){e=e||0,e=Math.min(e,.048),"
        "T._sdt=T._sdt==null?e:T._sdt*.872+e*.128,T.deltaRatio=T._sdt/.016,t=t||Date.now();"
        "var n=T.speed+(1-T.initialAmimation)*T._sdt*100;e=T._sdt*n,"
    )
    if _c_old not in js2:
        raise SystemExit("patch_particle_js: expected c() timestep body not found (source changed?)")
    js2 = js2.replace(_c_old, _c_new, 1)
    js2 = js2.replace("T.mouse.lerp(T.tmpMouse,.05)", "T.mouse.lerp(T.tmpMouse,.032)", 1)
    js2 = js2.replace("antialias:!1,alpha:!0", "antialias:!0,alpha:!0", 1)
    js2 = js2.replace('n.motionBlurQuality="high"', 'n.motionBlurQuality="best"', 1)
    # Spectrum: rotate four key colours in HSL (was fixed blue/teal hex) + faster shader lerp to match.
    _l_old = "function l(e){n.needsResetWorldMatrix"
    _l_new = (
        "function l(e){this._pmHueR=((this._pmHueR||0)+e*1.2)%1;var b=this._pmHueR;"
        "this.color1.setHSL(b,0.9,0.58);"
        "this.color2.setHSL((b+0.24)%1,0.87,0.54);"
        "this.color3.setHSL(0.572,1,0.67);"
        "this.color4.setHSL(0.598,0.94,0.56);"
        "n.needsResetWorldMatrix"
    )
    if _l_old not in js2:
        raise SystemExit("patch_particle_js: particle motion l(e) hook not found (source changed?)")
    js2 = js2.replace(_l_old, _l_new, 1)
    _lerp_old = (
        "this.uniforms.u_color1.value.lerp(this.color1,e),"
        "this.uniforms.u_color2.value.lerp(this.color2,e),"
        "this.uniforms.u_color3.value.lerp(this.color3,e),"
        "this.uniforms.u_color4.value.lerp(this.color4,e)"
    )
    _lerp_new = (
        "this.uniforms.u_color1.value.lerp(this.color1,Math.min(1,20*e)),"
        "this.uniforms.u_color2.value.lerp(this.color2,Math.min(1,20*e)),"
        "this.uniforms.u_color3.value.lerp(this.color3,Math.min(1,20*e)),"
        "this.uniforms.u_color4.value.lerp(this.color4,Math.min(1,20*e))"
    )
    if _lerp_old not in js2:
        raise SystemExit("patch_particle_js: u_color lerp block not found (source changed?)")
    js2 = js2.replace(_lerp_old, _lerp_new, 1)
    return js2


def main() -> None:
    if not SRC_CSS.is_file():
        raise SystemExit(f"Missing {SRC_CSS}")
    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    (LANDING / "js").mkdir(parents=True, exist_ok=True)
    (LANDING / "images").mkdir(parents=True, exist_ok=True)

    scoped = scope_landing_css(SRC_CSS.read_text(encoding="utf-8"))
    # Hero is title-only (overlay has no .logo-byline); keep block compact vs two-line layout.
    scoped = scoped.replace("min-height: 77px;", "min-height: 56px;", 1)
    OUT_CSS.write_text(scoped, encoding="utf-8")

    shutil.copyfile(SRC_THREE, LANDING / "js" / "three.r76.min.js")
    shutil.copyfile(SRC_TW, LANDING / "js" / "TweenMax.min.js")
    OUT_JS.write_text(patch_particle_js(SRC_JS.read_text(encoding="utf-8")), encoding="utf-8")

    print("Wrote", OUT_CSS, "and", OUT_JS)


if __name__ == "__main__":
    main()
