# -*- coding: utf-8 -*-
"""Generate landing/ assets from Particle Source extract. Run from repo root."""
from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PARTICLE = ROOT / "Particle"
if not (PARTICLE / "experiments" / "cymatics" / "index.html").is_file():
    PARTICLE = ROOT / "_extract_particle" / "Particle"
SRC_CSS = PARTICLE / "css" / "particle-love.com" / "css" / "index.css"
SRC_JS = PARTICLE / "js" / "particle-love.com" / "js" / "index.js"
SRC_THREE = PARTICLE / "js" / "particle-love.com" / "js" / "three.r76.min.js"
SRC_TW = PARTICLE / "js" / "particle-love.com" / "js" / "TweenMax.min.js"
LANDING = ROOT / "landing"
OUT_CSS = LANDING / "css" / "landing.css"
OUT_JS = LANDING / "js" / "particle-landing.js"

ROOT_HEADER = """/* Scoped for Cymatics Portal landing overlay — generated by _landing_assets.py */
#landing-root {
    position: fixed;
    inset: 0;
    z-index: 9000;
    font-family: 'Courier New', Courier, monospace;
    font-style: normal;
    background-color: #060a11;
    overflow: hidden;
    -webkit-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
}

"""


def _prefix_selector_line(sel: str) -> str:
    sel = sel.strip()
    if not sel or sel.startswith("#landing-root"):
        return sel
    parts = [p.strip() for p in sel.split(",")]
    out = []
    for p in parts:
        if p.startswith("#landing-root"):
            out.append(p)
        elif p.startswith("::") or p.startswith(":"):
            out.append(f"#landing-root {p}")
        else:
            out.append(f"#landing-root {p}")
    return ", ".join(out)


def scope_landing_css(css: str) -> str:
    css = re.sub(r"html\s*\{[^}]*\}", "", css, count=1)
    css = re.sub(r"body\s*\{[^}]*\}", "", css, count=1)
    lines = css.split("\n")
    out_lines: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if not stripped:
            out_lines.append(line)
            continue
        if stripped.startswith("/*"):
            out_lines.append(line)
            continue
        if stripped.startswith("@media"):
            out_lines.append(line)
            continue
        if stripped.startswith("@"):
            out_lines.append(line)
            continue

        if "{" in line:
            idx = line.index("{")
            before = line[:idx]
            after = line[idx:]
            indent = before[: len(before) - len(before.lstrip())]
            sel = before.strip()
            if sel:
                new_sel = _prefix_selector_line(sel)
                out_lines.append(f"{indent}{new_sel} {after}")
            else:
                out_lines.append(line)
        else:
            out_lines.append(line)
    return ROOT_HEADER + "\n".join(out_lines).strip() + "\n"


def patch_particle_js(js: str) -> str:
    """Point texture loads to ./landing/images/ (config.assetPath + images/motion_blur.png)."""
    repl_obj = (
        '(typeof window!=="undefined"&&window.__pmAssetPath)?'
        'window.__pmAssetPath:"./landing/"'
    )
    repl_assign = (
        '((typeof window!=="undefined"&&window.__pmAssetPath)?'
        'window.__pmAssetPath:"./landing/")'
    )
    js2 = js.replace('assetPath:"./"', f"assetPath:{repl_obj}")
    js2 = js2.replace('assetPath="./"', f"assetPath={repl_assign}")
    # Spectrum: rotate four key colours in HSL (was fixed blue/teal hex).
    _l_old = "function l(e){n.needsResetWorldMatrix"
    _l_new = (
        "function l(e){this._pmHueR=((this._pmHueR||0)+e*1.2)%1;var b=this._pmHueR;"
        "this.color1.setHSL(b,0.9,0.58);"
        "this.color2.setHSL((b+0.24)%1,0.87,0.54);"
        "this.color3.setHSL(0.572,1,0.67);"
        "this.color4.setHSL(0.598,0.94,0.56);"
        "n.needsResetWorldMatrix"
    )
    if _l_old not in js2:
        raise SystemExit("patch_particle_js: particle motion l(e) hook not found (source changed?)")
    js2 = js2.replace(_l_old, _l_new, 1)

    # Low-tier bootstrap at WebGL init: bridge Low click fires later; avoids 512²+MB hitch until handlers run.
    # Stock c()/mouse smoothing unchanged.
    _ptex_old = "particlesMotionTextureWidth=512,n.particlesMotionTextureHeight=512"
    _ptex_new = "particlesMotionTextureWidth=256,n.particlesMotionTextureHeight=256"
    if _ptex_old not in js2:
        raise SystemExit("patch_particle_js: particlesMotionTexture defaults not found (source changed?)")
    js2 = js2.replace(_ptex_old, _ptex_new, 1)
    _mb_old = 'n.motionBlur=!0;var o=n.motionBlurQualityMap'
    _mb_new = 'n.motionBlur=!1;var o=n.motionBlurQualityMap'
    if _mb_old not in js2:
        raise SystemExit("patch_particle_js: motionBlur default not found (source changed?)")
    js2 = js2.replace(_mb_old, _mb_new, 1)
    _mbq_old = 'n.motionBlurQualityList=r(o),n.motionBlurQuality="high"'
    _mbq_new = 'n.motionBlurQualityList=r(o),n.motionBlurQuality="low"'
    if _mbq_old not in js2:
        raise SystemExit("patch_particle_js: motionBlurQuality default not found (source changed?)")
    js2 = js2.replace(_mbq_old, _mbq_new, 1)
    _dpr_hook_old = "h=b.renderer,f=b.scene"
    _dpr_hook_new = (
        "h=b.renderer,h.setPixelRatio(Math.min(1.25,"
        '(typeof window!="undefined"?window.devicePixelRatio:1)||1)),f=b.scene'
    )
    if _dpr_hook_old not in js2:
        raise SystemExit("patch_particle_js: renderer assign (h=b.renderer) hook not found (source changed?)")
    js2 = js2.replace(_dpr_hook_old, _dpr_hook_new, 1)

    return js2


def main() -> None:
    if not SRC_CSS.is_file():
        raise SystemExit(f"Missing {SRC_CSS}")
    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    (LANDING / "js").mkdir(parents=True, exist_ok=True)
    (LANDING / "images").mkdir(parents=True, exist_ok=True)

    scoped = scope_landing_css(SRC_CSS.read_text(encoding="utf-8"))
    # Hero is title-only (overlay has no .logo-byline); keep block compact vs two-line layout.
    scoped = scoped.replace("min-height: 77px;", "min-height: 56px;", 1)
    OUT_CSS.write_text(scoped, encoding="utf-8")

    shutil.copyfile(SRC_THREE, LANDING / "js" / "three.r76.min.js")
    shutil.copyfile(SRC_TW, LANDING / "js" / "TweenMax.min.js")
    OUT_JS.write_text(patch_particle_js(SRC_JS.read_text(encoding="utf-8")), encoding="utf-8")

    print("Wrote", OUT_CSS, "and", OUT_JS)


if __name__ == "__main__":
    main()
